### ISSUE TITLE
[Question] ObservableAsPropertyHelper being readonly

### ISSUE THREAD

**Issue by CyLuGh** [wieslawsoltes/ReactiveGenerator#23]
Being super curious about source generation, I'm trying to switch from Fody to your library when working with ReactiveUI.

I've noticed that the backing field for **[ObservableAsProperty]** is set as readonly. I used to set the value to those when the viewmodel is activated (as they implement **IActivatableViewModel**).

```csharp
this.WhenActivated(disposables =>
{
    this.WhenAnyValue(x => x.Time)
        .Select(t => t.ToString())
        .ToProperty(
            this,
            x => x.CurrentDate,
            out _currentDateHelper,
            scheduler: customMainThreadScheduler
        )
        .DisposeWith(disposables);
});
```

Which is then incompatible with the readonly. 

Is there a specific reason for this choice?

**Comment by wieslawsoltes** [comment]
Not really any specific reason, we can make it not-readonly I guess. Will investigate.
